### ISSUE TITLE
Order of belongs_to in model effects results

### ISSUE THREAD

**Issue by jasper502** [danielpclark/PolyBelongsTo#14]
I am not sure if this is a bug or intentional.  I have a simple polymorphic Comment model:

  create_table "comments", force: :cascade do |t|
    t.integer  "user_id"
    t.integer  "commentable_id"
    t.string   "commentable_type"
    t.text     "note"
    t.string   "ancestry"
    t.datetime "created_at",       null: false
    t.datetime "updated_at",       null: false
  end

and my `comment.rb` file:

  belongs_to :user
  belongs_to :commentable, polymorphic: true

If I call `Comment.last.poly?` I get `false` and `Comment.last.pt_parent` results in the user from user_id.

When I switch it to:

  belongs_to :commentable, polymorphic: true
  belongs_to :user

I get `true` and the actual polymorphic parent resource.  This is actually what I expected and tried this from the model on a hunch.  The biggest issue here I see is that if you don't know this or change your model down the road you could easily break things.

**Comment by danielpclark** [comment]
I see your point.  I've written in the README that the Polymorphic relationships have precedence, but in the code it grabs the first parent relation which may or may not be Polymorphic.

> The biggest issue here I see is that if you don't know this or change your model down the road you could easily break things.

I won't make a breaking change without changing the Major version number on the project so as long as your code is properly version controlled you'll have no issue there.

The way I believe the priority should be is Polymorphic first.  I use the same structure as your example here on my own Polymorphic objects.  Where the user_id is an overall marker for you to know internally who owns the Object where as the polymorphic relation is the true ancestry to follow.

I do think this is worth amending.  I'll mark this change for version 1.0.0.  I also have some has_one and has_many methods I'm planning.

**Comment by danielpclark** [comment]
I will add tests to preserve behavior(s) pre 1.0.0.
