### ISSUE TITLE
pbt_parent fails with camel case model names?

### ISSUE THREAD

**Issue by jasper502** [danielpclark/PolyBelongsTo#16]
So I have a model `WorkOrder` and in my `work_order.rb` which contains:

`has_many :events, dependent: :destroy`

and an`Events` model and my `event.rb` which contains:

`belongs_to :work_order`

So in this example this is NOT a polymorphic relationship but PolyBelongsTo is supposed to work for any relationship and in my code if I call:

`Event.last.pbt_parent` I get:

`LoadError: Unable to autoload constant Work_order, expected ../work_order.rb to define it`

I am using PBT to figure out the parents of many of my models.  I have added a work around for this one for now.  Perhaps its not the camel case but it's just a hunch.

**Comment by danielpclark** [comment]
I'm sorry that I'm only now just seeing this.  I'm looking into it.

**Comment by danielpclark** [comment]
The fix has been released as gem version 0.2.9
